// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsnuEgsvSltYNUZv2FBVcx95Gmf9MCZjs',
    appId: '1:571795560797:web:ac1e296f32e22e397af0b4',
    messagingSenderId: '571795560797',
    projectId: 'tennis-app-315e3',
    authDomain: 'tennis-app-315e3.firebaseapp.com',
    storageBucket: 'tennis-app-315e3.appspot.com',
    measurementId: 'G-6Y5CK0HJDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHABk4urI0NdTAPzk9eL8MkEgxHcAx930',
    appId: '1:571795560797:android:a8a0243a5253f7b57af0b4',
    messagingSenderId: '571795560797',
    projectId: 'tennis-app-315e3',
    storageBucket: 'tennis-app-315e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_cMtGTYgl8ci6q5k0EOLLAEZUdvZ6OO0',
    appId: '1:571795560797:ios:4a0a88b2e032190e7af0b4',
    messagingSenderId: '571795560797',
    projectId: 'tennis-app-315e3',
    storageBucket: 'tennis-app-315e3.appspot.com',
    iosBundleId: 'com.example.tennisAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_cMtGTYgl8ci6q5k0EOLLAEZUdvZ6OO0',
    appId: '1:571795560797:ios:4a0a88b2e032190e7af0b4',
    messagingSenderId: '571795560797',
    projectId: 'tennis-app-315e3',
    storageBucket: 'tennis-app-315e3.appspot.com',
    iosBundleId: 'com.example.tennisAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsnuEgsvSltYNUZv2FBVcx95Gmf9MCZjs',
    appId: '1:571795560797:web:d4d2533c5fd445967af0b4',
    messagingSenderId: '571795560797',
    projectId: 'tennis-app-315e3',
    authDomain: 'tennis-app-315e3.firebaseapp.com',
    storageBucket: 'tennis-app-315e3.appspot.com',
    measurementId: 'G-VG18PR6B3Y',
  );
}
